### ISSUE TITLE
Single page application

### ISSUE THREAD

**Issue by gseidel** [indivisualvj/indivisual#8]
At the moment we have to run two windows, one for control and one for visualisation. It would be also nice to have both in one window. If someone just want to start visualisation as background, he just start the application, make some settings and close the control bar.

For professional use a two window application make sense, but it would be nice to use indivisual also as entertainment system e.g. for your tv in the living room.

**Comment by indivisualvj** [comment]
There is a basic version without collapsing the controller here: 
http://localhost:8081/inline.html

**Comment by indivisualvj** [comment]
fixed #13
